---
- name: Install apache
  hosts: webhosts
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present


    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy Html file to web server
      copy:
        src: ../web_test/index.html
        dest: /var/www/html/index.html