---
- name: Settings SSH
  hosts: webhosts
  become: yes
  vars:
    createuser: 'deploy_user'
    createpassword: "{{ 'nizam123@' | password_hash('sha512') }}"
    publickey_path: '/path/to/your/public_key.pub'
  
  tasks:
    - name: Setup | create user
      user:
        name: "{{ createuser }}"
        password: "{{ createpassword }}"
        shell: /bin/bash
        create_home: yes

    - name: Setup | authorized key upload
      authorized_key:
        user: "{{ createuser }}"
        key: "{{ lookup('file', publickey_path) }}"
        path: "/home/{{ createuser }}/.ssh/authorized_keys"
        manage_dir: yes
        state: present

    - name: Sudoers | update sudoers file and validate
      lineinfile:
        path: /etc/sudoers
        insertafter: EOF
        line: "{{ createuser }} ALL=(ALL) NOPASSWD: ALL"
        state: present
